seapath/build_debian_iso

srv_fai_config/package_config/SEAPATH

Kerberos/ldap/dns packages are useful to be able to join the seapath machines to
an ActiveDirectory domain.
Nullmailer is (for now) not used, and is installed by default. This
makes the machines try to resolve the "mail" hostname all the time.
Removing the package is the simplest solution.

packages: add dns/ldap/kerberos and force remove nullmailer

---

srv_fai_config/files/etc/default/grub.d/20_efi_ipv6.cfg/SEAPATH
srv_fai_config/files/etc/default/grub.d/20_ttyS0.cfg/SEAPATH
srv_fai_config/scripts/SEAPATH/20-grub_default

Having console=ttyS0 in the kernel boot parameters was useful for
testing on virtual machines ("virsh console" uses ttyS0...) however it
is problematic on real hardware.

Change Grub options: remove console=ttyS0

---

srv_fai_config/package_config/SEAPATH

Kerberos packages are useful to be able to join the seapath machines to
a ActiveDirectory domain.
Nullmailer is (for now) not used, and is installed by default. This
makes the machines try to resolve the "mail" hostname all the time.
Removing the package is the simplest solution.

packages: add dns/kerberos and remove nullmailer

---

build_iso.sh

we can write the file directly to the correct name and get rid of this extra "mv" operation

remove a useless mv operation

---

srv_fai_config/package_config/SEAPATH

this package comes with heavy dependancies (gcc..) and is not actually usefull for SEAPATH.

remove dracut from package list

---

srv_fai_config/disk_config/SEAPATH_LVM
srv_fai_config/disk_config/SEAPATH_LVM_EFI

The initrd file of the new kernel v6 is almost 50MB (it used to be 18MB on the v5 kernel).
This can saturate the /boot partition and make the upgrade fail. 500MB instead of 200MB for the /boot partition seems appropriate

increase the /boot partition to 500MB

---

srv_fai_config/package_config/SEAPATH

json parsing, useful to expose data to snmp for instance

packagelist: add jq

---

srv_fai_config/package_config/SEAPATH

To allow seapath to use ntp or ptp, the target system will use timemaster (provided by linuxptp).
Timemaster uses chrony to sync the hwclock with multiple clock (ptp, ntp)
The ansible playbooks will need to be updated.

replace timesyncd by chronyd

---

etc_fai/grub.cfg
srv_fai_config/class/50-seapath

Without this patch, the deployment needs a user to be physically connecter to the server (with keyboard and screen) to choose the profile.
With this commit, the SEAPATH_LVM profile is loaded by default. An upcoming commit will allow the user to preset an ip address on a specific NIC so that network is available right after deployement.

Allow the SEAPATH_LVM profile to be loaded by default

---

README.md
srv_fai_config/class/SEAPATH.var
srv_fai_config/scripts/SEAPATH/40-networking

This commit allow the user to configure ip addressing to a specified NIC so that remote access to the deployed server is possible right after deployment.
Along with the "no menu" feature that uses the SEAPATH_LVM profile by default, this allows a host to be deployed without even having to plug a screen and keyboard.

Set defaut networking

---

Dockerfile
docker-compose.yml
etc_fai/grub.cfg

A precedent commit allowed the deployment to start without the user to even to press enter.
Another one allowed the user to preconfigure a network configuration. With all that it should be possible to deploy a node without even having to plug a screen and keyboard on the machine.
However there still is the need to press ENTER at the end of the deployment, just before the reboot.
This commit fixes this by automating the end of deployment reboot.
The change is in the grub configuration, which was included in the docker image. This means to be taken into account, this fix would require the user to rebuild the docker image, which is painful. In order to change this, this commit also removes the /etc/fai configuration from the docker image and mount it as a container volume. That way any …

Reboot automatically after deployment

---

srv_fai_config/hooks/install.SEAPATH

FAI may choke when trying to remove the existing lvm volume groups, for instance when there are snapshots.
This commit makes the iso remove all the existing lvm volume groups before FAI starts the installation.

fai: remove all LVM volume groups before install

---

srv_fai_config/scripts/SEAPATH/60-misc

When the host is not configured (networking, ntp...) then timemaster can take several minutes to shutdown, which will make the host wait ages to reboot.
We disable timemaster service here, it will be re-enabled with the networking ansible playbook.

Disable Timemaster service

---

srv_fai_config/package_config/SEAPATH_DBG

Since vim is now in SEAPATH_COMMON

remove vim from SEAPATH_DBG

---

Dockerfile

Debian has upgraded to v12, with changes to the FAI version.
This codebase is (for now) only compatible with debian11.

Force debian11 docker image

---

srv_fai_config/class/SEAPATH_COMMON.var.defaults
srv_fai_config/disk_config/SEAPATH_RAID

- vars: change bookworm to bullseye to defaults vars : this will define the apt/sources.list file of the deployed machine
- ext4 inode: the correct option is -I and not -N

Silly typos

---

srv_fai_config/package_config/SEAPATH_VM

dbus is not installed when building a VM.

package_config: add dbus for the VM

---

srv_fai_config/class/BOOKWORM64.var
srv_fai_config/class/BULLSEYE64.var
srv_fai_config/class/SEAPATH_COMMON.var.defaults
srv_fai_config/disk_config/SEAPATH_HOST
srv_fai_config/package_config/SEAPATH_COMMON
srv_fai_config/package_config/SEAPATH_HOST

class: add bullseye and bookworm class for repo configuration
The list of repos in the /etc/apt/sources.list of the deployed machine will depends on those variables.
We add them in classes instead of the user having to specify this in its customization var file.
----
custom vars: customizing disklist
the scsi ordering in linux may not be deterministic (/dev/sda and /dev/sdb may switch depending on the hardware).
You can now customize the disklist by using /dev/disk/by-path/ links.
----
SEAPATH_HOST: add ipmitool
----
SEAPATH_COMMON: add parted package
parted is a dependency of ceph so is already present in SEAPATH_HOST but will be useful in SEAPATH_VM so that the customer can use ansible parted module to customize its guest partitionning.
cfdisk is present by default but there is no …

merge waiting changes

---

srv_fai_config/class/SEAPATH_COMMON.var.defaults
srv_fai_config/scripts/SEAPATH_COMMON/40-networking

Build_debian_iso configures the main network interface of the host so that host is directly accessible via networking after deployment.
In some network topologies, this main host network interface is a trunk, and the host needs to support vlan tagging to get access to the network.
This commit makes this topology supported, throught the use of the "REMOTEVLANID" configuration variable (in which the user simply has to set the vlanid number).

vlan on remote network

---

build_iso.sh
build_qcow2.sh
etc_fai/NFSROOT
etc_fai/apt/sources.list
etc_fai/grub.cfg
etc_fai/nfsroot.conf
srv_fai_config/class/99-seapath
srv_fai_config/package_config/SEAPATH_COMMON
srv_fai_config/package_config/SEAPATH_HOST

In accordance with SEAPATH TSC on Oct 12, 2023, this PR will make build_debian_iso generate seapath installation media based on debian 12.
The branch "debian11" has been created based on current main.

Debian12 upgrade

---

srv_fai_config/class/SEAPATH_COMMON.var.defaults

It does not work: for partition number FAI adds a number to the disk (/dev/sda --> /dev/sda1, /dev/sda2...). This pattern does not work with "by-path" (where we must use -part1, -part2...)
This reverts commit 575d6d8409b67f7bf2a3542b26b423ab35023aae.

Revert "custom vars: customizing disklist"

---

srv_fai_config/package_config/SEAPATH_HOST

This will allow the host to be able to read a windows guest disk to retrieve the disk occupation without agent

SEAPATH_HOST: add ntfs-3g to packages list

---

build_qcow2.sh

FAI's basefile for BOOKWORM64 is some months old right now. Using it triggers a udev upgrade that, with /dev bound into the chroot, change the ownership of /dev/kvm on the build host.
To avoid this, remove FAI basefile bootstrap, FAI will create a fresh basefile without triggering the problematic udev upgrade.
This increase build time by around 1 minute.

docker-compose.yml: Remove FAI basefile bootstrap

---

etc_fai/apt/sources.list

We include the standard bookworm version of FAI in the docker image (6.0.3), but FAI upgrades the version in the NFSROOT to the one present in the project repository (fai-project.org/download). The project recently upgraded this version to 6.2, giving an inconsistency between the build_debian_iso configuration (qualified for 6.0.3) and the actual used FAI version (6.2).
This commits prevent FAI to upgrade to 6.2 in the NFSROOT.

prevents FAI to upgrade to 6.2 in the NFSROOT

---

build_qcow2.sh

The upstream project considers qemu-img knows how to handle zstd compression and adapted FAI accordingly (https://github.com/faiproject/fai/commit/2a583d3bbfcc125c0f0c16dd2844ea52ca7a9d03?diff=split&w=0)
However the qemu-img present in bookworm does not yet support zstd compression.
This commit will rollback the change in build_debian_iso

build_qcow2: rollback upstream commit on qemu-img and zstd

---

build_iso.sh
build_qcow2.sh

docker compose v2 integrate with docker cli, in that case we must call compose with "docker compose" instead of "docker-compose".
This commits looks for "docker compose" and falls back to "docker-compose" if needed

build scripts: make them compatible with docker compose v2

---

.github/workflows/shellcheck-weekly.yml

This will allow us to trigger the shellcheck-weekly workflow from other workflows. This is needed to run shellcheck-weekly manually.

github/workflows: add workflow_call to shellcheck-weekly

---

.github/workflows/shellcheck.yml

This will allow the shellcheck workflow to be triggered by other workflows. This is useful for the weekly shellcheck workflow that will be triggered by the weekly workflow.

github/workflows: add workflow_call to shellcheck workflow

---

README.md
build_iso.sh
srv_fai_config/package_config/SEAPATH_COCKPIT

Hello,
This PR adds the ability to install Cockpit web UI into Seapath Debian.
To do so, a new class `SEAPATH_COCKPIT` has been created which add the following packages:
- `cockpit` (core package)
- `cockpit-machines` (plugin for VM management)
Once Seapath is installed on the target Cockpit web UI can be access though IP address on 9090 port.

Cockpit integration in Seapath Debian

---

srv_fai_config/package_config/SEAPATH_HOST

We have a lot of code for the purpose of tuning the host machines for real-time Latency.
The TuneD is a system tuning service can simplify the code and improve results.
Please see PR in the  seapath/ansible repo:
https://github.com/seapath/ansible/pull/444

Replace direct Real-Time tuning with Tuned.

---

build_qcow2.sh

build_qcow2: Fixes wrong path in new FAI version

---

srv_fai_config/package_config/SEAPATH_COCKPIT

Add the cockpit PackageKit plugin used to install Debian updates.

SEAPATH_COCKPIT: add package

---

srv_fai_config/disk_config/SEAPATH_HOST
srv_fai_config/disk_config/SEAPATH_RAID
srv_fai_config/disk_config/SEAPATH_RAID_DEMO

disk_config: /var/log LV renamed from vg1-log to vg1-varlog
This is to have the same LV name for all disk configurations
----
partitioning: make initial ceph VG and LV very small
There is an ansible playbook to increase those to the required sizes to be defined in the inventory

changes in partitionning for HOST and RAID flavors

---

.github/workflows/shellcheck-weekly.yml
.github/workflows/shellcheck.yml

Restrict permissions of the CI workflows:
fails
- `checks: write` allows validating the check.

.github/workflows: restrict permissions

---

.github/workflows/shellcheck.yml

see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

workflows: transition from node 16 to node 20

---

srv_fai_config/package_config/SEAPATH_DBG
srv_fai_config/package_config/SEAPATH_HOST

Added packages for realtime optimizations that I'd like to have included in the official image in SEAPATH_HOST.
Furthermore added packages in SEAPATH_DBG for more convenience.

SEAPATH_HOST: add intel-cmt-cat and msr-tools to packages list

---

.gitignore
README.md
build_iso.sh
build_qcow2.sh
srv_fai_config/class/98-seapath
srv_fai_config/class/SEAPATH_COMMON.var
user_classes.conf

Add the USERCUSTOMIZATION class to facilitate user configuration
This commits splits the base hierarchy into 3:
- srv_fai_config is still the default SEAPATH configuration
- usercustomization is the same hierarchy but git will not track it, and the user can put custom files in it
- build_tmp is a temporary folder where the installer will merge srv_fai_config and userconfiguration just before merging
srv_fai_config also includes now the new USERCUSTOMIZATION class, so that the files in the usercustomization/ folder can implement this class and override/add any setting.
----
Allows userdefined classes
With this commit the user can add his own classes by:
- adding the class in the user_classes.conf file
- dealing with a numbered script in usercustomization/class/ folder (for example …

Add the USERCUSTOMIZATION class and allow User-defined classes

---

build_iso.sh

This one was forgotten when moving to whiptail.

build_iso.sh: add SEAPATH_HOST to list of classes

---

srv_fai_config/package_config/SEAPATH_COMMON
srv_fai_config/scripts/SEAPATH_COMMON/40-networking

Netplan will now be used as a high level network configuration tool for SEAPATH.

SEAPATH_COMMON: add netplan

---

srv_fai_config/package_config/SEAPATH_COMMON

We do not need to use the backported version anymore. 6.6 contains all the features we need + it's LTS.

kernel version: use the debian stable version (6.6)

---

build_qcow2.sh

The USERCUSTOMIZATION feature allows the user to configure its own partitioning for the SEAPATH VM, however, the total disk size is hardcoded in the build_qcow2.sh script.
This commit introduces a optional parameter ro specify the target total disk size for a VM (-s / --vmdisksize).
Since this script is starting to have parameters, we also add an "--help" and "--version" parameter to help a user figure out the parameters.

build_qcow2: allows the VM disk size to be customized

---

srv_fai_config/package_config/SEAPATH_HOST

This package contains xmllint, a command line XML tool. It is used to validate the xml file and print the error if the file is not valid.
xmllinit is used by libvirt to add more information if the xml file is not valid. It is also used by the resource-agents VirtualDomain during the configuration saving.

SEAPATH_COMMON: add libxml2-utils

---

srv_fai_config/package_config/SEAPATH_HOST

needed for the snmp agent to work

snmp: add libsnmp-extension-passpersist-perl

---

srv_fai_config/class/SEAPATH_COMMON.var

It makes more sense to name it "admin" instead of "virtu"

SEAPATH_COMMON.var: change default admin username

---

srv_fai_config/package_config/SEAPATH_HOST

Needed for the new way of installing python packages (vm_manager and setup_ovs)

SEAPATH_HOST: adds python3-pip

---

docker-compose.yml

This commit adds the Z option to the volumes in the docker-compose file to support selinux. This is necessary to run the container on a system with selinux enabled.

docker-compose: add selinux support

---

srv_fai_config/package_config/SEAPATH_HOST

This is needed for an upcoping PR ("grub bootcount")

SEAPATH_HOST: adds patch package

---

build_iso.sh
etc_fai/grub_base.cfg

Newcomers will not want to use raid on SEAPATH.
Advanced user will use the '--custom' flag and add it manually.

build_iso.sh: disable raid by default
