seapath/build_debian_iso

srv_fai_config/package_config/SEAPATH

Add Tuna tool

---

srv_fai_config/files/etc/default/grub.d/20_efi_ipv6.cfg/SEAPATH
srv_fai_config/package_config/SEAPATH

Switch from docker-ce (docker) to docker-io (debian)

---

srv_fai_config/package_config/SEAPATH

typo in docker.io package name

---

build_iso.sh
srv_fai_config/scripts/SEAPATH/60-divers

Include docker image "php:apache" in iso

---

.gitignore
README.md
srv_fai_config/class/SEAPATH.var
srv_fai_config/scripts/SEAPATH/10-rootpw
srv_fai_config/scripts/SEAPATH/40-networking

Add an "ansible" user in the base installation

---

srv_fai_config/package_config/SEAPATH

Adding packages needed to get server temperature info

---

srv_fai_config/disk_config/SEAPATH_LVM
srv_fai_config/disk_config/SEAPATH_LVM_EFI

/boot filesystem as ext4 instead of ext2

---

.gitignore
README.md
srv_fai_config/class/SEAPATH.var.defaults
srv_fai_config/scripts/SEAPATH/40-networking

Move all settings to SEAPATH.var file + update documentation

---

srv_fai_config/scripts/SEAPATH/10-rootpw

Changing the ansible UID to 1005

---

srv_fai_config/package_config/SEAPATH

This PR adds packages needed to use auditd on target.

Add auditd packages

---

README.md

README.md : add status badge

---

srv_fai_config/package_config/SEAPATH

* Add cpu microcode for intel and amd to fully support them

package_config: add cpu microcode packages

---

README.md
srv_fai_config/class/60-kerberos
srv_fai_config/class/seapath.profile
srv_fai_config/package_config/KERBEROS
srv_fai_config/scripts/SEAPATH/70-apt_proxy

Define the new Kerberos FAI configuration.
SFL: #9314
Change-Id: I0f3b488ec29c2394f22595eb23e94a8e858fccfc

fai: add Kerberos class

---

build_iso.sh
srv_fai_config/scripts/SEAPATH/10-rootpw

This PR restrict the rights of the ansible user to use sudo

Ansi bp 028 r39

---

srv_fai_config/package_config/SEAPATH_COMMON

very useful for pretty editing

package list: add vim

---

srv_fai_config/package_config/SEAPATH_COMMON
srv_fai_config/package_config/SEAPATH_HOST

package_config: install snmp only for HOST

---

.github/workflows/shellcheck-weekly.yml

Add a weekly shellcheck workflow that will run every saturday at 22:30.

github/workflows: add shellcheck-weekly

---

srv_fai_config/package_config/SEAPATH_HOST

useful for xml conversion in the snmp scripts

Add xmltodict python3 module

---

srv_fai_config/scripts/SEAPATH_HOST/61-misc

see discussion https://github.com/seapath/ansible/pull/429

disable nginx.service

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Modify issue templates to fit SEAPATH.

.github/ISSUE_TEMPLATE
